package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func TestSecurityOpenCodePluginFailsClosed(t *testing.T) {
	node, err := exec.LookPath("node")
	if err != nil {
		if os.Getenv("CI") != "" {
			t.Fatal("node is required in CI to execute the generated OpenCode plugin")
		}
		t.Skip("node is required to execute the generated OpenCode plugin")
	}

	tests := []struct {
		name       string
		gateOutput string
		gateExit   int
		want       string
	}{
		{"policy_block", `{"allow":false,"reason":"policy denied"}`, 0, "blocked\n"},
		{"gate_failure_without_payload_exit_zero", "", 0, "blocked\n"},
		{"gate_failure_without_payload", "", 3, "blocked\n"},
		{"gate_failure_with_allow_payload", `{"allow":true}`, 3, "blocked\n"},
		{"allow", `{"allow":true}`, 0, "allowed\n"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			dir := t.TempDir()
			writeExecutable(t, filepath.Join(dir, "edictum"), fmt.Sprintf("#!/bin/sh\ncat >/dev/null\nprintf '%%s' %s\nexit %d\n", shellQuote(test.gateOutput), test.gateExit))
			if err := os.WriteFile(filepath.Join(dir, "edictum-gate.mjs"), []byte(opencodePluginContent), 0o600); err != nil {
				t.Fatal(err)
			}
			runner := `import { EdictumGate } from "./edictum-gate.mjs";
const plugin = await EdictumGate({ directory: process.cwd() });
try {
  await plugin["tool.execute.before"]({ tool: "bash" }, { args: { command: "echo ok" } });
  console.log("allowed");
} catch (_) {
  console.log("blocked");
}
`
			runnerPath := filepath.Join(dir, "runner.mjs")
			if err := os.WriteFile(runnerPath, []byte(runner), 0o600); err != nil {
				t.Fatal(err)
			}

			cmd := exec.Command(node, runnerPath)
			cmd.Dir = dir
			cmd.Env = append(os.Environ(), "PATH="+dir+string(os.PathListSeparator)+os.Getenv("PATH"))
			output, err := cmd.CombinedOutput()
			if err != nil {
				t.Fatalf("running generated plugin: %v\n%s", err, output)
			}
			if string(output) != test.want {
				t.Fatalf("plugin result = %q, want %q", output, test.want)
			}
		})
	}
}

func TestInstallOpenCodeRefreshesGeneratedPlugin(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	pluginDir := filepath.Join(home, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0o755); err != nil {
		t.Fatal(err)
	}
	pluginPath := filepath.Join(pluginDir, "edictum-gate.ts")
	legacy := opencodeGeneratedPluginSignature + `
// Generated by an earlier Edictum release.
const command = "edictum gate check --format opencode";
`
	if err := os.WriteFile(pluginPath, []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}
	before, err := os.Stat(pluginPath)
	if err != nil {
		t.Fatal(err)
	}

	message, err := installOpenCode()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(message, "Updated edictum gate plugin") {
		t.Fatalf("message = %q, want update confirmation", message)
	}
	got, err := os.ReadFile(pluginPath)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != opencodePluginContent {
		t.Fatal("existing generated plugin was not refreshed")
	}
	after, err := os.Stat(pluginPath)
	if err != nil {
		t.Fatal(err)
	}
	if os.SameFile(before, after) {
		t.Fatal("generated plugin was rewritten in place instead of replaced atomically")
	}

	message, err = installOpenCode()
	if err != nil {
		t.Fatal(err)
	}
	if message != "Edictum gate plugin already installed for OpenCode" {
		t.Fatalf("message = %q, want already-installed confirmation", message)
	}
}

func TestInstallOpenCodeRefusesUnrecognizedFile(t *testing.T) {
	tests := []struct {
		name    string
		content string
	}{
		{"unrelated_plugin", "// user-managed plugin\n"},
		{"user_managed_gate_wrapper", "// user-managed plugin\nconst command = \"edictum gate check --format opencode\";\n"},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			home := t.TempDir()
			t.Setenv("HOME", home)
			pluginDir := filepath.Join(home, ".opencode", "plugins")
			if err := os.MkdirAll(pluginDir, 0o755); err != nil {
				t.Fatal(err)
			}
			pluginPath := filepath.Join(pluginDir, "edictum-gate.ts")
			original := []byte(test.content)
			if err := os.WriteFile(pluginPath, original, 0o644); err != nil {
				t.Fatal(err)
			}

			_, err := installOpenCode()
			if err == nil || !strings.Contains(err.Error(), "refusing to overwrite") {
				t.Fatalf("error = %v, want overwrite refusal", err)
			}
			got, readErr := os.ReadFile(pluginPath)
			if readErr != nil {
				t.Fatal(readErr)
			}
			if string(got) != string(original) {
				t.Fatal("unrecognized existing plugin was modified")
			}
		})
	}
}

func TestShellQuoteRoundTrip(t *testing.T) {
	sh, err := exec.LookPath("sh")
	if err != nil {
		t.Skip("sh is required to verify POSIX shell quoting")
	}
	want := `Rule 'no-rm': blocked`
	output, err := exec.Command(sh, "-c", "printf '%s' "+shellQuote(want)).CombinedOutput()
	if err != nil {
		t.Fatalf("shell quote command failed: %v\n%s", err, output)
	}
	if string(output) != want {
		t.Fatalf("shell quote round trip = %q, want %q", output, want)
	}
}

func writeExecutable(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o755); err != nil {
		t.Fatal(err)
	}
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
