// gate_assistants_cleanup.go — Cleanup-only uninstall support for gate
// integrations removed from the supported install and check surfaces.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const (
	legacyCursorCommand       = "edictum gate check --format cursor"
	legacyGeminiCommand       = ".gemini/hooks/edictum-gate.sh"
	legacyGeminiGeneratedMark = "# Generated by: edictum gate install gemini"
)

func uninstallLegacyCursor() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	hooksPath := filepath.Join(home, ".cursor", "hooks.json")
	config, err := readJSONFile(hooksPath)
	if os.IsNotExist(err) {
		return "No Cursor hooks found", nil
	}
	if err != nil {
		return "", fmt.Errorf("reading Cursor hooks: %w", err)
	}

	hooks, _ := config["hooks"].(map[string]any)
	if hooks == nil {
		return "Edictum gate hook not found in Cursor hooks", nil
	}
	preToolUse, _ := hooks["preToolUse"].([]any)
	filtered, removed := filterLegacyCursorEntries(preToolUse)
	if !removed {
		return "Edictum gate hook not found in Cursor hooks", nil
	}

	hooks["preToolUse"] = filtered
	config["hooks"] = hooks
	if err := writeJSONFileAtomic(hooksPath, config); err != nil {
		return "", err
	}
	return fmt.Sprintf("Removed legacy edictum gate hook from %s", hooksPath), nil
}

func filterLegacyCursorEntries(entries []any) ([]any, bool) {
	filtered := make([]any, 0, len(entries))
	removed := false
	for _, entry := range entries {
		m, _ := entry.(map[string]any)
		command, _ := m["command"].(string)
		if strings.TrimSpace(command) == legacyCursorCommand {
			removed = true
			continue
		}
		filtered = append(filtered, entry)
	}
	return filtered, removed
}

func uninstallLegacyGemini() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	settingsPath := filepath.Join(cwd, ".gemini", "settings.json")
	scriptPath := filepath.Join(cwd, ".gemini", "hooks", "edictum-gate.sh")

	settings, settingsErr := readJSONFile(settingsPath)
	if settingsErr != nil && !os.IsNotExist(settingsErr) {
		return "", fmt.Errorf("reading Gemini settings: %w", settingsErr)
	}
	script, scriptErr := os.ReadFile(scriptPath) //nolint:gosec // Fixed cleanup path inside the working directory.
	if scriptErr != nil && !os.IsNotExist(scriptErr) {
		return "", fmt.Errorf("reading Gemini hook script: %w", scriptErr)
	}

	removedSetting := false
	if settingsErr == nil {
		if hooks, _ := settings["hooks"].(map[string]any); hooks != nil {
			beforeTool, _ := hooks["BeforeTool"].([]any)
			filtered, removed := filterLegacyGeminiEntries(beforeTool)
			if removed {
				hooks["BeforeTool"] = filtered
				settings["hooks"] = hooks
				if err := writeJSONFileAtomic(settingsPath, settings); err != nil {
					return "", err
				}
				removedSetting = true
			}
		}
	}

	removedScript := false
	if scriptErr == nil && strings.Contains(string(script), legacyGeminiGeneratedMark) {
		if err := os.Remove(scriptPath); err != nil {
			return "", err
		}
		removedScript = true
	}

	if removedSetting || removedScript {
		return fmt.Sprintf("Removed legacy edictum gate hook from %s", filepath.Join(cwd, ".gemini")), nil
	}
	return "Edictum gate hook not found for Gemini CLI", nil
}

func filterLegacyGeminiEntries(entries []any) ([]any, bool) {
	filtered := make([]any, 0, len(entries))
	removed := false
	for _, entry := range entries {
		m, _ := entry.(map[string]any)
		if m == nil {
			filtered = append(filtered, entry)
			continue
		}
		hooks, _ := m["hooks"].([]any)
		clean := make([]any, 0, len(hooks))
		for _, hook := range hooks {
			hm, _ := hook.(map[string]any)
			name, _ := hm["name"].(string)
			command, _ := hm["command"].(string)
			if name == "edictum-gate" && command == legacyGeminiCommand {
				removed = true
				continue
			}
			clean = append(clean, hook)
		}
		if len(clean) > 0 {
			m["hooks"] = clean
			filtered = append(filtered, m)
		}
	}
	return filtered, removed
}
