// gate_assistants_ext.go — Copilot, Gemini, and OpenCode install/uninstall
// logic, plus assistant detection for gate status.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// --- Copilot ---

func installCopilot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	hooksPath := filepath.Join(cwd, ".github", "hooks", "hooks.json")
	config, err := readJSONFile(hooksPath)
	if err != nil {
		config = map[string]any{}
	}

	if _, ok := config["version"]; !ok {
		config["version"] = float64(1)
	}

	hookEntry := map[string]any{
		"type": "command", "bash": "edictum gate check --format copilot", "timeoutSec": float64(5),
	}
	hooks := ensureMap(config, "hooks")
	preToolUse := ensureSlice(hooks, "preToolUse")

	if containsHookMarkerDirect(preToolUse, "bash") {
		return "Edictum gate hook already installed for Copilot CLI", nil
	}

	preToolUse = append(preToolUse, hookEntry)
	hooks["preToolUse"] = preToolUse
	config["hooks"] = hooks

	if wErr := writeJSONFileAtomic(hooksPath, config); wErr != nil {
		return "", wErr
	}
	return fmt.Sprintf("Installed edictum gate hook in %s", hooksPath), nil
}

func uninstallCopilot() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	hooksPath := filepath.Join(cwd, ".github", "hooks", "hooks.json")
	config, err := readJSONFile(hooksPath)
	if err != nil {
		return "No Copilot CLI hooks found", nil //nolint:nilerr // File not found is not an error for uninstall.
	}

	hooks, _ := config["hooks"].(map[string]any)
	if hooks == nil {
		return "Edictum gate hook not found in Copilot CLI hooks", nil
	}
	preToolUse, _ := hooks["preToolUse"].([]any)

	filtered, removed := filterDirectEntries(preToolUse, "bash")
	if !removed {
		return "Edictum gate hook not found in Copilot CLI hooks", nil
	}

	hooks["preToolUse"] = filtered
	config["hooks"] = hooks
	if wErr := writeJSONFileAtomic(hooksPath, config); wErr != nil {
		return "", wErr
	}
	return fmt.Sprintf("Removed edictum gate hook from %s", hooksPath), nil
}

// --- Gemini CLI ---

const geminiHookScript = `#!/usr/bin/env bash
# Edictum Gate hook for Gemini CLI
# Generated by: edictum gate install gemini
input=$(cat)
result=$(echo "$input" | edictum gate check --format gemini 2>&1)
exit_code=$?
if [ $exit_code -eq 1 ]; then
  echo "$result" >&2
  exit 1
fi
# Fail-closed: if edictum is missing or crashed (non-0, non-1), deny the call
if [ $exit_code -ne 0 ]; then
  echo "Edictum gate check failed (exit $exit_code)" >&2
  exit 1
fi
echo "{}"
exit 0
`

func installGemini() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	settingsPath := filepath.Join(cwd, ".gemini", "settings.json")

	if existing, rErr := readJSONFile(settingsPath); rErr == nil {
		if containsGeminiHook(existing) {
			return "Edictum gate hook already installed for Gemini CLI", nil
		}
	}

	hooksDir := filepath.Join(cwd, ".gemini", "hooks")
	if mkErr := os.MkdirAll(hooksDir, 0o755); mkErr != nil {
		return "", mkErr
	}
	scriptPath := filepath.Join(hooksDir, "edictum-gate.sh")
	if wErr := os.WriteFile(scriptPath, []byte(geminiHookScript), 0o755); wErr != nil { //nolint:gosec // Hook script must be executable.
		return "", wErr
	}

	settings, _ := readJSONFile(settingsPath)
	if settings == nil {
		settings = map[string]any{}
	}
	hookEntry := map[string]any{
		"matcher": "*",
		"hooks": []any{
			map[string]any{
				"name":    "edictum-gate",
				"type":    "command",
				"command": ".gemini/hooks/edictum-gate.sh",
			},
		},
	}
	hooks := ensureMap(settings, "hooks")
	beforeTool := ensureSlice(hooks, "BeforeTool")
	beforeTool = append(beforeTool, hookEntry)
	hooks["BeforeTool"] = beforeTool
	settings["hooks"] = hooks

	if wErr := writeJSONFileAtomic(settingsPath, settings); wErr != nil {
		return "", wErr
	}
	return fmt.Sprintf("Installed edictum gate hook at %s (registered in %s)", scriptPath, settingsPath), nil
}

func uninstallGemini() (string, error) {
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	scriptPath := filepath.Join(cwd, ".gemini", "hooks", "edictum-gate.sh")
	settingsPath := filepath.Join(cwd, ".gemini", "settings.json")

	removedScript := false
	if _, sErr := os.Stat(scriptPath); sErr == nil {
		if rmErr := os.Remove(scriptPath); rmErr == nil {
			removedScript = true
		}
	}

	removedSetting := false
	if settings, rErr := readJSONFile(settingsPath); rErr == nil {
		hooks, _ := settings["hooks"].(map[string]any)
		if hooks != nil {
			beforeTool, _ := hooks["BeforeTool"].([]any)
			filtered, did := filterGeminiEntries(beforeTool)
			if did {
				removedSetting = true
				hooks["BeforeTool"] = filtered
				settings["hooks"] = hooks
				_ = writeJSONFileAtomic(settingsPath, settings)
			}
		}
	}

	if removedScript || removedSetting {
		return fmt.Sprintf("Removed edictum gate hook from %s", filepath.Join(cwd, ".gemini")), nil
	}
	return "Edictum gate hook not found for Gemini CLI", nil
}

func containsGeminiHook(settings map[string]any) bool {
	hooks, _ := settings["hooks"].(map[string]any)
	if hooks == nil {
		return false
	}
	beforeTool, _ := hooks["BeforeTool"].([]any)
	for _, entry := range beforeTool {
		m, _ := entry.(map[string]any)
		if m == nil {
			continue
		}
		hs, _ := m["hooks"].([]any)
		for _, h := range hs {
			hm, _ := h.(map[string]any)
			if hm == nil {
				continue
			}
			name, _ := hm["name"].(string)
			cmd, _ := hm["command"].(string)
			if strings.Contains(name, "edictum") || strings.Contains(cmd, "edictum") {
				return true
			}
		}
	}
	return false
}

func filterGeminiEntries(entries []any) ([]any, bool) {
	var filtered []any
	removed := false
	for _, entry := range entries {
		m, _ := entry.(map[string]any)
		if m == nil {
			filtered = append(filtered, entry)
			continue
		}
		hs, _ := m["hooks"].([]any)
		var clean []any
		for _, h := range hs {
			hm, _ := h.(map[string]any)
			if hm == nil {
				clean = append(clean, h)
				continue
			}
			name, _ := hm["name"].(string)
			cmd, _ := hm["command"].(string)
			if strings.Contains(name, "edictum") || strings.Contains(cmd, "edictum") {
				removed = true
				continue
			}
			clean = append(clean, h)
		}
		if len(clean) > 0 {
			m["hooks"] = clean
			filtered = append(filtered, m)
		}
	}
	return filtered, removed
}
