// gate_assistants_detect.go — OpenCode install/uninstall and installed
// assistant detection for gate status.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// --- OpenCode ---

const opencodePluginContent = `// Edictum Gate plugin for OpenCode
// Generated by: edictum gate install opencode
import { spawnSync } from "child_process";

export const EdictumGate = async ({ directory }) => {
  return {
    "tool.execute.before": async (input, output) => {
      const payload = JSON.stringify({
        tool: input.tool,
        args: output.args,
        directory: directory || process.cwd(),
      });
      try {
        const proc = spawnSync(
          "edictum",
          ["gate", "check", "--format", "opencode"],
          { input: payload, encoding: "utf-8", timeout: 5000, shell: false }
        );
        if (proc.error) {
          throw new Error("Edictum gate check failed: " + proc.error.message);
        }
        const result = (proc.stdout || "").trim();
        if (!result) return;
        const parsed = JSON.parse(result);
        if (parsed.allow === false) {
          throw new Error(parsed.reason || "Denied by edictum gate");
        }
      } catch (e) {
        if (e.message && e.message.startsWith("Denied")) throw e;
        if (e.message && e.message.startsWith("Contract")) throw e;
        // Fail-closed: unknown error blocks the tool call
        throw new Error("Edictum gate check failed: " + e.message);
      }
    }
  };
};
`

func installOpenCode() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	pluginsDir := filepath.Join(home, ".opencode", "plugins")
	if mkErr := os.MkdirAll(pluginsDir, 0o755); mkErr != nil {
		return "", mkErr
	}
	pluginPath := filepath.Join(pluginsDir, "edictum-gate.ts")

	if data, rErr := os.ReadFile(pluginPath); rErr == nil { //nolint:gosec // Known path under ~/.opencode.
		if strings.Contains(string(data), edictumHookMarker) {
			return "Edictum gate plugin already installed for OpenCode", nil
		}
	}

	if wErr := os.WriteFile(pluginPath, []byte(opencodePluginContent), 0o644); wErr != nil { //nolint:gosec // Plugin file needs to be readable.
		return "", wErr
	}
	return fmt.Sprintf("Installed edictum gate plugin at %s", pluginPath), nil
}

func uninstallOpenCode() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	pluginPath := filepath.Join(home, ".opencode", "plugins", "edictum-gate.ts")

	if _, sErr := os.Stat(pluginPath); os.IsNotExist(sErr) {
		return "Edictum gate plugin not found for OpenCode", nil
	}
	if rmErr := os.Remove(pluginPath); rmErr != nil {
		return "", rmErr
	}
	return fmt.Sprintf("Removed edictum gate plugin from %s", pluginPath), nil
}

// ---------------------------------------------------------------------------
// Detect installed assistants (for status)
// ---------------------------------------------------------------------------

func detectInstalledAssistants() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}
	var installed []string

	// Claude Code.
	if settings, rErr := readJSONFile(filepath.Join(home, ".claude", "settings.json")); rErr == nil {
		hooks, _ := settings["hooks"].(map[string]any)
		if hooks != nil {
			ptu, _ := hooks["PreToolUse"].([]any)
			if containsHookMarker(ptu, "hooks", "command") {
				installed = append(installed, "claude-code")
			}
		}
	}

	// Cursor.
	if config, rErr := readJSONFile(filepath.Join(home, ".cursor", "hooks.json")); rErr == nil {
		hooks, _ := config["hooks"].(map[string]any)
		if hooks != nil {
			ptu, _ := hooks["preToolUse"].([]any)
			if containsHookMarkerDirect(ptu, "command") {
				installed = append(installed, "cursor")
			}
		}
	}

	// Copilot (cwd-relative).
	if cwd, cwdErr := os.Getwd(); cwdErr == nil {
		if config, rErr := readJSONFile(filepath.Join(cwd, ".github", "hooks", "hooks.json")); rErr == nil {
			hooks, _ := config["hooks"].(map[string]any)
			if hooks != nil {
				ptu, _ := hooks["preToolUse"].([]any)
				if containsHookMarkerDirect(ptu, "bash") {
					installed = append(installed, "copilot")
				}
			}
		}
	}

	// Gemini (cwd-relative).
	if cwd, cwdErr := os.Getwd(); cwdErr == nil {
		scriptPath := filepath.Join(cwd, ".gemini", "hooks", "edictum-gate.sh")
		if _, sErr := os.Stat(scriptPath); sErr == nil {
			installed = append(installed, "gemini")
		}
	}

	// OpenCode.
	pluginPath := filepath.Join(home, ".opencode", "plugins", "edictum-gate.ts")
	if _, sErr := os.Stat(pluginPath); sErr == nil {
		installed = append(installed, "opencode")
	}

	return installed
}
